services:
  jupyter:
    build:
      context: .
      target: jupyter
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./work/notebooks:/work/notebooks
      - ./work/src:/work/src
      - ./work/input:/work/input
      - ./examples:/work/examples
      - ./models/:/work/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: "16gb"
